In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#１：リストの作成
sample_list = [1,2,3,4,5]
sample_list

#Numpyを使って、配列を作成
sample_array = np.array([1,2,3,4,5])
sample_array

np.array([1,2,'A'])

array(['1', '2', 'A'], dtype='<U21')

In [ ]:
#２：Numpy配列の演算
print(sample_array + 1)
print(sample_array * 2)

[2 3 4 5 6]
[ 2  4  6  8 10]


In [ ]:
#３：Numpyの2次元配列
sample_array_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(sample_array_2)

print(sample_array_2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
#４：等差数列の作成
print(np.arange(start=1,stop=6,step=1))
print(np.arange(start=0.1,stop=0.8,step=0.2))
print(np.linspace(start=1,stop=5,num=5))
print(np.linspace(start=1,stop=5,num=11))
print(np.linspace(start=0.1,stop=0.7,num=4))

[1 2 3 4 5]
[0.1 0.3 0.5 0.7]
[1. 2. 3. 4. 5.]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]
[0.1 0.3 0.5 0.7]


In [ ]:
#５：様々なアレイの作成

#要素を指定回数繰り返し並べた配列
print(np.tile('A',5))
#0を4回並べた配列
print(np.tile(0,4))
#0.0の初期化された配列で要素は4つ
print(np.zeros(4))
#2次元の0.0配列で2行3列
print(np.zeros([2,3]))
#1.0で初期化された配列
print(np.ones(3))

['A' 'A' 'A' 'A' 'A']
[0 0 0 0]
[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]


In [ ]:
#６：スライス、範囲指定で配列要素を取得

#1次元配列の作成
d1_array = np.array([1,2,3,4,5])
print(d1_array)
#配列の0番目の要素を取り出す
print(d1_array[0])
#インデックス1番と2番の要素をまとめて取り出す
print(d1_array[[1,2]])
#スライス（範囲指定）で、インデックス1から2までの要素を取り出す
print(d1_array[1:3])
#二次元（2D）配列を作成
d2_array = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10]])
print(d2_array)
#0行目・3列目の要素を取り出す
print(d2_array[0,3])
#1行目の2列目から3列目まで（4列目未満）を取り出す
print(d2_array[1,2:4])

[1 2 3 4 5]
1
[2 3]
[2 3]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4
[8 9]


In [ ]:
#７：データフレーム
sample_df = pd.DataFrame({
    'col1':sample_array,
    'col2':sample_array*2,
    'col3':['A','B','C','D','E']
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E


In [31]:
from google.colab import files
uploaded = files.upload()

Saving 2-4-1-sample_data.csv to 2-4-1-sample_data.csv


In [32]:
#８：ファイルデータの読み込み
file_data = pd.read_csv('2-4-1-sample_data.csv')
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [33]:
#９：データフレームの結合
df_1 = pd.DataFrame({
    'col1' : np.array([1,2,3]),
    'col2' : np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
#縦方向に結合
print(pd.concat([df_1,df_2]))

#横方向に結合
print(pd.concat([df_1,df_2],axis = 1))

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F
   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F


In [39]:
#１０：特定の列を取得・削除
print(sample_df)
#col2を取得
print("------------------")
print(sample_df.col2)
print("------------------")
print(sample_df['col2'])
print("------------------")
#複数列を抽出
print(sample_df[['col2','col3']])
print("------------------")
#特定の列を削除
print(sample_df.drop('col1',axis=1))

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E
------------------
0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64
------------------
0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64
------------------
   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E
   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    E


In [42]:
#１１：行の抽出

#最初の3行を取得
print(sample_df.head(n=3))
print("------------------")
#抽出条件を指定
print(sample_df.query('index == 0'))
print("------------------")
#col3という列の値がAである行のみを抽出
print(sample_df.query('col3 == "A"'))
print("------------------")
#OR条件の抽出
print(sample_df.query('col3 == "A" | col3 == "D"'))
print("------------------")
#AND条件の抽出
print(sample_df.query('col3 == "A" & col1 == 3'))
print("------------------")
#行と列の抽出
print(sample_df.query('col3 == "A"')[['col2','col3']])

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
------------------
   col1  col2 col3
0     1     2    A
------------------
   col1  col2 col3
0     1     2    A
------------------
   col1  col2 col3
0     1     2    A
3     4     8    D
------------------
Empty DataFrame
Columns: [col1, col2, col3]
Index: []
------------------
   col2 col3
0     2    A


In [43]:
#１２：DataFrame型の列や行のSeries型をNumpy配列に変換

#PandasのDataFrame型
print(type(sample_df))
#col1列だけを取り出す。型はSeries型
print(type(sample_df.col1))
#col1列をNumPy配列に変換
print(type(np.array(sample_df.col1)))
#Pandasの公式な変換メソッドを使って、NumPy配列に変換
print(type(sample_df.col1.to_numpy()))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
